import os
from dataclasses import dataclass
from typing import Tuple

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM


@dataclass(frozen=True)
class EncryptedData:
    """
    Container for encrypted data with all components needed for decryption.

    Attributes:
        ciphertext: Encrypted bytes.
        iv: Initialization vector (nonce) used for encryption (12 bytes for GCM).
        tag: Authentication tag for GCM mode (16 bytes).
    """

    ciphertext: bytes
    iv: bytes
    tag: bytes


def generate_aes_key(key_size: int = 256) -> bytes:
    """
    Generate a cryptographically secure AES key.

    Args:
        key_size: Key size in bits (128, 192, or 256). Default is 256.

    Returns:
        Random bytes representing the key (32 bytes for AES-256).

    Raises:
        ValueError: If key_size is not a valid AES key size.
    """
    valid_sizes = {128: 16, 192: 24, 256: 32}

    if key_size not in valid_sizes:
        raise ValueError(f"Key size must be one of {list(valid_sizes.keys())} bits")

    return os.urandom(valid_sizes[key_size])


def encrypt_aes_256_gcm(plaintext: bytes, key: bytes) -> EncryptedData:
    """
    Encrypt data using AES-256 in GCM mode.

    GCM (Galois/Counter Mode) provides both confidentiality and authenticity.

    Args:
        plaintext: Bytes to encrypt.
        key: AES-256 key (32 bytes). Use generate_aes_key() to generate a secure key.

    Returns:
        EncryptedData containing ciphertext, IV (nonce), and authentication tag.

    Raises:
        ValueError: If key length is not 32 bytes (for AES-256).
        TypeError: If plaintext or key are not bytes.
    """
    if not isinstance(plaintext, bytes):
        raise TypeError("Plaintext must be bytes")
    if not isinstance(key, bytes):
        raise TypeError("Key must be bytes")
    if len(key) != 32:
        raise ValueError("Key must be 32 bytes (256 bits) for AES-256")

    # Generate a random 12-byte nonce (IV) for GCM
    iv = os.urandom(12)

    # Create cipher object with AES-256-GCM
    cipher = Cipher(algorithms.AES(key), modes.GCM(iv))
    encryptor = cipher.encryptor()

    # Encrypt plaintext
    ciphertext = encryptor.update(plaintext) + encryptor.finalize()

    # Extract authentication tag (16 bytes, generated by encryptor)
    tag = encryptor.tag

    return EncryptedData(ciphertext=ciphertext, iv=iv, tag=tag)


def decrypt_aes_256_gcm(encrypted_data: EncryptedData, key: bytes) -> bytes:
    """
    Decrypt data encrypted with AES-256-GCM.

    Args:
        encrypted_data: EncryptedData containing ciphertext, IV, and tag.
        key: AES-256 key (32 bytes). Must be the same key used for encryption.

    Returns:
        Original plaintext bytes.

    Raises:
        ValueError: If key length is incorrect or authentication fails.
        TypeError: If key is not bytes.
        cryptography.exceptions.InvalidTag: If ciphertext has been tampered with
            or wrong key is used (authentication failure).
    """
    if not isinstance(key, bytes):
        raise TypeError("Key must be bytes")
    if len(key) != 32:
        raise ValueError("Key must be 32 bytes (256 bits) for AES-256")

    # Create cipher object with AES-256-GCM using stored IV and tag
    cipher = Cipher(algorithms.AES(key), modes.GCM(encrypted_data.iv, encrypted_data.tag))
    decryptor = cipher.decryptor()

    # Decrypt ciphertext (will raise InvalidTag if authentication fails)
    plaintext = decryptor.update(encrypted_data.ciphertext) + decryptor.finalize()

    return plaintext


def encrypt_aes_256_gcm_raw(plaintext: bytes, key: bytes) -> Tuple[bytes, bytes, bytes]:
    """
    Encrypt data using AES-256-GCM and return raw components.

    Returns ciphertext, IV, and tag as separate bytes for flexible serialization.

    Args:
        plaintext: Bytes to encrypt.
        key: AES-256 key (32 bytes).

    Returns:
        Tuple of (ciphertext, iv, tag) as bytes.

    Raises:
        ValueError: If key length is not 32 bytes.
        TypeError: If plaintext or key are not bytes.
    """
    encrypted_data = encrypt_aes_256_gcm(plaintext, key)
    return encrypted_data.ciphertext, encrypted_data.iv, encrypted_data.tag


def decrypt_aes_256_gcm_raw(
    ciphertext: bytes, iv: bytes, tag: bytes, key: bytes
) -> bytes:
    """
    Decrypt data using AES-256-GCM from raw components.

    Args:
        ciphertext: Encrypted bytes.
        iv: Initialization vector (nonce), 12 bytes for GCM.
        tag: Authentication tag, 16 bytes.
        key: AES-256 key (32 bytes).

    Returns:
        Original plaintext bytes.

    Raises:
        ValueError: If key length is incorrect.
        TypeError: If inputs are not bytes.
        cryptography.exceptions.InvalidTag: If authentication fails.
    """
    encrypted_data = EncryptedData(ciphertext=ciphertext, iv=iv, tag=tag)
    return decrypt_aes_256_gcm(encrypted_data, key)
